#!/usr/bin/env bash
#check if the length of ars is sup than 4
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

#variables
path_to_file="$1"
ip="$2"
username="$3"
path_to_ssh_key="$4"

#Strict host key checking must be disabled when using scp
scp -o StrictHostKeyChecking=no -i "$path_to_ssh_key" "$path_to_file" "$username"@"$ip":~/
