#!/usr/bin/env bash

# Update package index
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Create index.html file with "Hello World!" content
echo "Hello World!" > /var/www/html/index.html

# Restart nginx (without using systemctl)
sudo service nginx start
