#!/usr/bin/env bash
sed -i 's/user www-data;/user nginx/' /etc/nginx/nginx.conf
sed -i '/listen 80 default_server/c\    listen 8080 default_server' /etc/nginx/sites-available/default
systemctl stop apache2
pkill apache2
service nginx restart
